# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in aoc23.gemspec
# gemspec

gem "rake", "~> 13.0"
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development

gem "parallel", "~> 1.23"

gem "scanf", "~> 1.0"

gem "pry", "~> 0.14.2"
