# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in aoc23.gemspec
# gemspec

gem "rake", "~> 13.0"
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
