local lpeg = require 'lpeg'
-- grammar
grammar = {A42 = ((lpeg.V("A9") * lpeg.V("A14")) + (lpeg.V("A10") * lpeg.V("A1"))), 
A9 = ((lpeg.V("A14") * lpeg.V("A27")) + (lpeg.V("A1") * lpeg.V("A26"))), 
A10 = ((lpeg.V("A23") * lpeg.V("A14")) + (lpeg.V("A28") * lpeg.V("A1"))), 
A1 = lpeg.P("a"), 
A11 = (lpeg.V("A42") * lpeg.V("A31")), 
A5 = ((lpeg.V("A1") * lpeg.V("A14")) + (lpeg.V("A15") * lpeg.V("A1"))), 
A19 = ((lpeg.V("A14") * lpeg.V("A1")) + (lpeg.V("A14") * lpeg.V("A14"))), 
A12 = ((lpeg.V("A24") * lpeg.V("A14")) + (lpeg.V("A19") * lpeg.V("A1"))), 
A16 = ((lpeg.V("A15") * lpeg.V("A1")) + (lpeg.V("A14") * lpeg.V("A14"))), 
A31 = ((lpeg.V("A14") * lpeg.V("A17")) + (lpeg.V("A1") * lpeg.V("A13"))), 
A6 = ((lpeg.V("A14") * lpeg.V("A14")) + (lpeg.V("A1") * lpeg.V("A14"))), 
A2 = ((lpeg.V("A1") * lpeg.V("A24")) + (lpeg.V("A14") * lpeg.V("A4"))), 
A0 = (lpeg.V("A8") * lpeg.V("A11")), 
A13 = ((lpeg.V("A14") * lpeg.V("A3")) + (lpeg.V("A1") * lpeg.V("A12"))), 
A15 = ((lpeg.V("A1")) + (lpeg.V("A14"))), 
A17 = ((lpeg.V("A14") * lpeg.V("A2")) + (lpeg.V("A1") * lpeg.V("A7"))), 
A23 = ((lpeg.V("A25") * lpeg.V("A1")) + (lpeg.V("A22") * lpeg.V("A14"))), 
A28 = (lpeg.V("A16") * lpeg.V("A1")), 
A4 = (lpeg.V("A1") * lpeg.V("A1")), 
A20 = ((lpeg.V("A14") * lpeg.V("A14")) + (lpeg.V("A1") * lpeg.V("A15"))), 
A3 = ((lpeg.V("A5") * lpeg.V("A14")) + (lpeg.V("A16") * lpeg.V("A1"))), 
A27 = ((lpeg.V("A1") * lpeg.V("A6")) + (lpeg.V("A14") * lpeg.V("A18"))), 
A14 = lpeg.P("b"), 
A21 = ((lpeg.V("A14") * lpeg.V("A1")) + (lpeg.V("A1") * lpeg.V("A14"))), 
A25 = ((lpeg.V("A1") * lpeg.V("A1")) + (lpeg.V("A1") * lpeg.V("A14"))), 
A22 = (lpeg.V("A14") * lpeg.V("A14")), 
A8 = (lpeg.V("A42")), 
A26 = ((lpeg.V("A14") * lpeg.V("A22")) + (lpeg.V("A1") * lpeg.V("A20"))), 
A18 = (lpeg.V("A15") * lpeg.V("A15")), 
A7 = ((lpeg.V("A14") * lpeg.V("A5")) + (lpeg.V("A1") * lpeg.V("A21"))), 
A24 = (lpeg.V("A14") * lpeg.V("A1"))}

input = {
"abbbbbabbbaaaababbaabbbbabababbbabbbbbbabaaaa", 
"bbabbbbaabaabba", 
"babbbbaabbbbbabbbbbbaabaaabaaa", 
"aaabbbbbbaaaabaababaabababbabaaabbababababaaa", 
"bbbbbbbaaaabbbbaaabbabaaa", 
"bbbababbbbaaaaaaaabbababaaababaabab", 
"ababaaaaaabaaab", 
"ababaaaaabbbaba", 
"baabbaaaabbaaaababbaababb", 
"abbbbabbbbaaaababbbbbbaaaababb", 
"aaaaabbaabaaaaababaa", 
"aaaabbaaaabbaaa", 
"aaaabbaabbaaaaaaabbbabbbaaabbaabaaa", 
"babaaabbbaaabaababbaabababaaab", 
"aabbbbbaabbbaaaaaabbbbbababaaaaabbaaabba"
}
return {grammar = grammar, input = input}
