local lpeg = require 'lpeg'
-- grammar
grammar = {A62 = (lpeg.V("A93") * lpeg.V("A93")), 
A41 = ((lpeg.V("A40") * lpeg.V("A111")) + (lpeg.V("A127") * lpeg.V("A70"))), 
A95 = ((lpeg.V("A127") * lpeg.V("A93")) + (lpeg.V("A40") * lpeg.V("A40"))), 
A73 = ((lpeg.V("A127") * lpeg.V("A24")) + (lpeg.V("A40") * lpeg.V("A58"))), 
A121 = ((lpeg.V("A127") * lpeg.V("A82")) + (lpeg.V("A40") * lpeg.V("A75"))), 
A101 = (lpeg.V("A93") * lpeg.V("A95")), 
A54 = ((lpeg.V("A127") * lpeg.V("A64")) + (lpeg.V("A40") * lpeg.V("A112"))), 
A76 = ((lpeg.V("A71") * lpeg.V("A40")) + (lpeg.V("A106") * lpeg.V("A127"))), 
A25 = ((lpeg.V("A50") * lpeg.V("A40")) + (lpeg.V("A126") * lpeg.V("A127"))), 
A21 = (lpeg.V("A127") * lpeg.V("A65")), 
A111 = ((lpeg.V("A65") * lpeg.V("A40")) + (lpeg.V("A57") * lpeg.V("A127"))), 
A44 = ((lpeg.V("A127") * lpeg.V("A127")) + (lpeg.V("A127") * lpeg.V("A40"))), 
A120 = ((lpeg.V("A98") * lpeg.V("A127")) + (lpeg.V("A108") * lpeg.V("A40"))), 
A59 = ((lpeg.V("A40") * lpeg.V("A111")) + (lpeg.V("A127") * lpeg.V("A34"))), 
A63 = ((lpeg.V("A65") * lpeg.V("A40")) + (lpeg.V("A65") * lpeg.V("A127"))), 
A8 = (lpeg.V("A42")), 
A106 = ((lpeg.V("A44") * lpeg.V("A40")) + (lpeg.V("A50") * lpeg.V("A127"))), 
A98 = ((lpeg.V("A127") * lpeg.V("A48")) + (lpeg.V("A40") * lpeg.V("A13"))), 
A1 = ((lpeg.V("A36") * lpeg.V("A127")) + (lpeg.V("A74") * lpeg.V("A40"))), 
A52 = ((lpeg.V("A127") * lpeg.V("A20")) + (lpeg.V("A40") * lpeg.V("A114"))), 
A114 = ((lpeg.V("A50") * lpeg.V("A127")) + (lpeg.V("A88") * lpeg.V("A40"))), 
A2 = ((lpeg.V("A29") * lpeg.V("A40")) + (lpeg.V("A45") * lpeg.V("A127"))), 
A57 = ((lpeg.V("A127") * lpeg.V("A127")) + (lpeg.V("A40") * lpeg.V("A127"))), 
A65 = (lpeg.V("A40") * lpeg.V("A40")), 
A43 = ((lpeg.V("A40") * lpeg.V("A89")) + (lpeg.V("A127") * lpeg.V("A73"))), 
A42 = ((lpeg.V("A40") * lpeg.V("A69")) + (lpeg.V("A127") * lpeg.V("A5"))), 
A110 = ((lpeg.V("A127") * lpeg.V("A122")) + (lpeg.V("A40") * lpeg.V("A128"))), 
A83 = ((lpeg.V("A40") * lpeg.V("A30")) + (lpeg.V("A127") * lpeg.V("A103"))), 
A105 = ((lpeg.V("A110") * lpeg.V("A40")) + (lpeg.V("A53") * lpeg.V("A127"))), 
A19 = ((lpeg.V("A116") * lpeg.V("A127")) + (lpeg.V("A59") * lpeg.V("A40"))), 
A90 = ((lpeg.V("A40") * lpeg.V("A40")) + (lpeg.V("A127") * lpeg.V("A127"))), 
A75 = (lpeg.V("A93") * lpeg.V("A90")), 
A11 = (lpeg.V("A42") * lpeg.V("A31")), 
A20 = ((lpeg.V("A127") * lpeg.V("A61")) + (lpeg.V("A40") * lpeg.V("A62"))), 
A16 = ((lpeg.V("A83") * lpeg.V("A127")) + (lpeg.V("A12") * lpeg.V("A40"))), 
A33 = ((lpeg.V("A65") * lpeg.V("A127")) + (lpeg.V("A62") * lpeg.V("A40"))), 
A4 = ((lpeg.V("A81") * lpeg.V("A127")) + (lpeg.V("A91") * lpeg.V("A40"))), 
A10 = (lpeg.V("A40") * lpeg.V("A57")), 
A18 = ((lpeg.V("A61") * lpeg.V("A40")) + (lpeg.V("A62") * lpeg.V("A127"))), 
A88 = ((lpeg.V("A40") * lpeg.V("A127")) + (lpeg.V("A127") * lpeg.V("A40"))), 
A102 = ((lpeg.V("A40") * lpeg.V("A109")) + (lpeg.V("A127") * lpeg.V("A107"))), 
A49 = ((lpeg.V("A9") * lpeg.V("A127")) + (lpeg.V("A51") * lpeg.V("A40"))), 
A81 = ((lpeg.V("A25") * lpeg.V("A127")) + (lpeg.V("A84") * lpeg.V("A40"))), 
A115 = ((lpeg.V("A104") * lpeg.V("A40")) + (lpeg.V("A106") * lpeg.V("A127"))), 
A125 = ((lpeg.V("A43") * lpeg.V("A40")) + (lpeg.V("A92") * lpeg.V("A127"))), 
A9 = ((lpeg.V("A93") * lpeg.V("A127")) + (lpeg.V("A127") * lpeg.V("A40"))), 
A130 = ((lpeg.V("A106") * lpeg.V("A40")) + (lpeg.V("A67") * lpeg.V("A127"))), 
A56 = ((lpeg.V("A95") * lpeg.V("A40")) + (lpeg.V("A57") * lpeg.V("A127"))), 
A34 = (lpeg.V("A40") * lpeg.V("A44")), 
A77 = ((lpeg.V("A127") * lpeg.V("A55")) + (lpeg.V("A40") * lpeg.V("A124"))), 
A79 = ((lpeg.V("A27") * lpeg.V("A40")) + (lpeg.V("A13") * lpeg.V("A127"))), 
A80 = ((lpeg.V("A40") * lpeg.V("A41")) + (lpeg.V("A127") * lpeg.V("A52"))), 
A82 = ((lpeg.V("A126") * lpeg.V("A127")) + (lpeg.V("A61") * lpeg.V("A40"))), 
A61 = ((lpeg.V("A40") * lpeg.V("A40")) + (lpeg.V("A40") * lpeg.V("A127"))), 
A27 = ((lpeg.V("A51") * lpeg.V("A40")) + (lpeg.V("A95") * lpeg.V("A127"))), 
A94 = ((lpeg.V("A40") * lpeg.V("A127")) + (lpeg.V("A93") * lpeg.V("A40"))), 
A6 = ((lpeg.V("A78") * lpeg.V("A127")) + (lpeg.V("A129") * lpeg.V("A40"))), 
A24 = ((lpeg.V("A61") * lpeg.V("A127")) + (lpeg.V("A50") * lpeg.V("A40"))), 
A126 = (lpeg.V("A127") * lpeg.V("A40")), 
A108 = ((lpeg.V("A82") * lpeg.V("A40")) + (lpeg.V("A56") * lpeg.V("A127"))), 
A29 = ((lpeg.V("A127") * lpeg.V("A62")) + (lpeg.V("A40") * lpeg.V("A61"))), 
A70 = (lpeg.V("A127") * lpeg.V("A95")), 
A99 = ((lpeg.V("A90") * lpeg.V("A127")) + (lpeg.V("A61") * lpeg.V("A40"))), 
A127 = lpeg.P("b"), 
A124 = ((lpeg.V("A15") * lpeg.V("A127")) + (lpeg.V("A120") * lpeg.V("A40"))), 
A48 = ((lpeg.V("A40") * lpeg.V("A65")) + (lpeg.V("A127") * lpeg.V("A50"))), 
A74 = ((lpeg.V("A50") * lpeg.V("A127")) + (lpeg.V("A61") * lpeg.V("A40"))), 
A55 = ((lpeg.V("A40") * lpeg.V("A66")) + (lpeg.V("A127") * lpeg.V("A16"))), 
A64 = (lpeg.V("A40") * lpeg.V("A9")), 
A109 = ((lpeg.V("A127") * lpeg.V("A88")) + (lpeg.V("A40") * lpeg.V("A95"))), 
A112 = ((lpeg.V("A40") * lpeg.V("A94")) + (lpeg.V("A127") * lpeg.V("A9"))), 
A30 = ((lpeg.V("A44") * lpeg.V("A127")) + (lpeg.V("A61") * lpeg.V("A40"))), 
A47 = ((lpeg.V("A121") * lpeg.V("A127")) + (lpeg.V("A130") * lpeg.V("A40"))), 
A28 = ((lpeg.V("A27") * lpeg.V("A40")) + (lpeg.V("A56") * lpeg.V("A127"))), 
A23 = ((lpeg.V("A48") * lpeg.V("A40")) + (lpeg.V("A97") * lpeg.V("A127"))), 
A96 = ((lpeg.V("A40") * lpeg.V("A95")) + (lpeg.V("A127") * lpeg.V("A65"))), 
A37 = ((lpeg.V("A63") * lpeg.V("A40")) + (lpeg.V("A7") * lpeg.V("A127"))), 
A116 = ((lpeg.V("A123") * lpeg.V("A127")) + (lpeg.V("A36") * lpeg.V("A40"))), 
A7 = ((lpeg.V("A40") * lpeg.V("A44")) + (lpeg.V("A127") * lpeg.V("A65"))), 
A35 = (lpeg.V("A40") * lpeg.V("A127")), 
A69 = ((lpeg.V("A40") * lpeg.V("A125")) + (lpeg.V("A127") * lpeg.V("A72"))), 
A36 = ((lpeg.V("A65") * lpeg.V("A127")) + (lpeg.V("A94") * lpeg.V("A40"))), 
A123 = ((lpeg.V("A127") * lpeg.V("A65")) + (lpeg.V("A40") * lpeg.V("A57"))), 
A85 = ((lpeg.V("A40") * lpeg.V("A126")) + (lpeg.V("A127") * lpeg.V("A65"))), 
A39 = ((lpeg.V("A9") * lpeg.V("A127")) + (lpeg.V("A126") * lpeg.V("A40"))), 
A26 = ((lpeg.V("A127") * lpeg.V("A35")) + (lpeg.V("A40") * lpeg.V("A88"))), 
A5 = ((lpeg.V("A22") * lpeg.V("A127")) + (lpeg.V("A100") * lpeg.V("A40"))), 
A60 = ((lpeg.V("A40") * lpeg.V("A90")) + (lpeg.V("A127") * lpeg.V("A65"))), 
A71 = ((lpeg.V("A9") * lpeg.V("A127")) + (lpeg.V("A61") * lpeg.V("A40"))), 
A78 = ((lpeg.V("A40") * lpeg.V("A82")) + (lpeg.V("A127") * lpeg.V("A39"))), 
A87 = ((lpeg.V("A21") * lpeg.V("A40")) + (lpeg.V("A101") * lpeg.V("A127"))), 
A46 = ((lpeg.V("A126") * lpeg.V("A127")) + (lpeg.V("A44") * lpeg.V("A40"))), 
A66 = ((lpeg.V("A127") * lpeg.V("A54")) + (lpeg.V("A40") * lpeg.V("A37"))), 
A13 = ((lpeg.V("A127") * lpeg.V("A61")) + (lpeg.V("A40") * lpeg.V("A50"))), 
A91 = ((lpeg.V("A40") * lpeg.V("A119")) + (lpeg.V("A127") * lpeg.V("A99"))), 
A31 = ((lpeg.V("A77") * lpeg.V("A40")) + (lpeg.V("A105") * lpeg.V("A127"))), 
A38 = ((lpeg.V("A60") * lpeg.V("A40")) + (lpeg.V("A106") * lpeg.V("A127"))), 
A128 = ((lpeg.V("A38") * lpeg.V("A40")) + (lpeg.V("A2") * lpeg.V("A127"))), 
A3 = ((lpeg.V("A46") * lpeg.V("A40")) + (lpeg.V("A49") * lpeg.V("A127"))), 
A117 = ((lpeg.V("A44") * lpeg.V("A127")) + (lpeg.V("A95") * lpeg.V("A40"))), 
A17 = ((lpeg.V("A14") * lpeg.V("A40")) + (lpeg.V("A79") * lpeg.V("A127"))), 
A84 = ((lpeg.V("A127") * lpeg.V("A65")) + (lpeg.V("A40") * lpeg.V("A65"))), 
A45 = ((lpeg.V("A90") * lpeg.V("A127")) + (lpeg.V("A95") * lpeg.V("A40"))), 
A86 = ((lpeg.V("A127") * lpeg.V("A18")) + (lpeg.V("A40") * lpeg.V("A85"))), 
A72 = ((lpeg.V("A40") * lpeg.V("A80")) + (lpeg.V("A127") * lpeg.V("A4"))), 
A103 = (lpeg.V("A93") * lpeg.V("A62")), 
A50 = ((lpeg.V("A93") * lpeg.V("A127")) + (lpeg.V("A40") * lpeg.V("A40"))), 
A104 = ((lpeg.V("A35") * lpeg.V("A40")) + (lpeg.V("A65") * lpeg.V("A127"))), 
A89 = ((lpeg.V("A117") * lpeg.V("A127")) + (lpeg.V("A46") * lpeg.V("A40"))), 
A51 = (lpeg.V("A127") * lpeg.V("A127")), 
A107 = ((lpeg.V("A90") * lpeg.V("A40")) + (lpeg.V("A88") * lpeg.V("A127"))), 
A0 = (lpeg.V("A8") * lpeg.V("A11")), 
A32 = ((lpeg.V("A40") * lpeg.V("A102")) + (lpeg.V("A127") * lpeg.V("A115"))), 
A113 = ((lpeg.V("A96") * lpeg.V("A40")) + (lpeg.V("A26") * lpeg.V("A127"))), 
A14 = ((lpeg.V("A10") * lpeg.V("A40")) + (lpeg.V("A24") * lpeg.V("A127"))), 
A58 = ((lpeg.V("A50") * lpeg.V("A127")) + (lpeg.V("A126") * lpeg.V("A40"))), 
A15 = ((lpeg.V("A23") * lpeg.V("A127")) + (lpeg.V("A87") * lpeg.V("A40"))), 
A68 = ((lpeg.V("A1") * lpeg.V("A40")) + (lpeg.V("A28") * lpeg.V("A127"))), 
A40 = lpeg.P("a"), 
A119 = ((lpeg.V("A65") * lpeg.V("A40")) + (lpeg.V("A50") * lpeg.V("A127"))), 
A12 = ((lpeg.V("A40") * lpeg.V("A33")) + (lpeg.V("A127") * lpeg.V("A56"))), 
A118 = ((lpeg.V("A57") * lpeg.V("A127")) + (lpeg.V("A35") * lpeg.V("A40"))), 
A122 = ((lpeg.V("A113") * lpeg.V("A127")) + (lpeg.V("A3") * lpeg.V("A40"))), 
A67 = ((lpeg.V("A127") * lpeg.V("A9")) + (lpeg.V("A40") * lpeg.V("A126"))), 
A22 = ((lpeg.V("A68") * lpeg.V("A40")) + (lpeg.V("A47") * lpeg.V("A127"))), 
A92 = ((lpeg.V("A86") * lpeg.V("A40")) + (lpeg.V("A76") * lpeg.V("A127"))), 
A93 = ((lpeg.V("A127")) + (lpeg.V("A40"))), 
A129 = ((lpeg.V("A84") * lpeg.V("A127")) + (lpeg.V("A118") * lpeg.V("A40"))), 
A97 = ((lpeg.V("A88") * lpeg.V("A127")) + (lpeg.V("A65") * lpeg.V("A40"))), 
A100 = ((lpeg.V("A17") * lpeg.V("A40")) + (lpeg.V("A19") * lpeg.V("A127"))), 
A53 = ((lpeg.V("A40") * lpeg.V("A6")) + (lpeg.V("A127") * lpeg.V("A32")))}

input = {
"aabbbabaabbbbababaaababbaaaaaaaa", 
"babaabbbaaaabbbbaababbabbabaaaabbabaabba", 
"abbbaabbbbaabababbaaaababbabbbba", 
"bbaabbabbbaaabbbbbaaaaab", 
"aaabbaaaaabbabbaabaababa", 
"bbabbabbaabbabbbbbabbaab", 
"aababbaabbbabaaabbababbbabaaabbbbbaabaaabbbbaaabaabbabbaaabbabaabbbaaaababbbabaaaabbabbb", 
"abaabbaaaaaaababbbbbaaaa", 
"abaababaabaaabbbabababaabbaaababbabbbbbabbbabababbabbabbabbbbaab", 
"bbabbababbbbbabbbabbaaba", 
"babbbaaababbbbababaaabbbbaabbbab", 
"babaabbbbbababaabbbabbaa", 
"aaaaaabbaaabbabaabaabaaa", 
"aabbbbbbaaababbaababbbaaaaabababbaabbbab", 
"aabbbbbabaabbabaaababbabbbaaabaa", 
"babbbbbabbbaababaabaabbaaabbbbbbaaaaaaaa", 
"aabbbbaaaaaaaabbabbbbbbaaabbaabaaabbaaaabbababba", 
"ababaabbbaabbbbaabbbabab", 
"aaabaabbaaabaaaaaaaabbba", 
"aabbbabbbbbababbbababaaaabbabbbb", 
"bbbbabaabbaabbbabababbab", 
"bbbababbbbaaabbbbbbaaaba", 
"bbbabaaaabaabbaaaababbaa", 
"abbaaabbbbbabbbbbabababa", 
"baaabbabababbabbabbaabab", 
"babaabbbabbaaaabbbabaabaaabaaaaaabbabbab", 
"ababbbabbbbbbabbaaabaaabaaaabbaaabbbaabb", 
"abbbaabababaaaababbaaaaaaabababaaaababbb", 
"bababaaabaaaabbbaaababbb", 
"aaabaaabbaabbabaabababbbabbbbbaababbabaa", 
"abbbbabbbaaaaaabababbbabbbbaabbbaabababa", 
"aabaaabaabaabbbbbbaabbbabaaaaaabbababbbbaaaabaaa", 
"babbaabbaabaababaaaaaaab", 
"baabbababbabababbbaabaabaabaabbaaababbaaaaaabbaa", 
"aabbaaaabaabbbbaabbbbaab", 
"bbaaabbaababaabaaababaababbabaab", 
"aaabbaabababbbbaaabababbabbbabbaaaabababbabaaaaaabaabaaaaaaabbbabaaaabaa", 
"babbbbbbbaabaaaaabababab", 
"abbaaaaabaaabbaaababaabbbababaaabbbababaaaabbbaabaabaaba", 
"aaaaaabbbbbababbaaabaaababbabbababababab", 
"bbbabaaabbaababbabaababaaaabbbbbaababbba", 
"aaabbbbabbbbabaababbaaabababbaaabaaabbaabababaabaabbbaba", 
"baabbabababbbbbaaababbabbabbbabb", 
"bbbaababbabaabbabbbaabababababbbbbabaabb", 
"bababbababbaabababaababbbabaabbbbbbaababbbaabbaabbaaaabaabaaaaba", 
"abbbaaaaaabababbbbaaabab", 
"bbaabbbaabaabbbaabaaabab", 
"aabaabababbaabaaabbabaaaabbabbaaaababbbaaaabbabbbaaaabbbbaaaabbbbaabbabb", 
"aababbbbababbababbaabbababaababaaaaaaaabbaaaabbabaababbbabbbabaabbaababbbbaababb", 
"abbaaaabbbabbabaababaaaa", 
"babbaaaaaaababbababaaaaa", 
"bbbbaabbbbaaabbabbaababa", 
"ababbbabaabbbabbabaababa", 
"abbababbaabbbbbaabbbbbabaaabbbab", 
"aaabbbaaababaabbaabababbababaaaaaaabaabaabbaabbb", 
"bbaabbabbaabbbaabbbbabba", 
"aaaaaabbabbbaaaabaabaabbabbbbaba", 
"bbbbbabbababbbaaabaaabbbbbbbabbaaaaaabbb", 
"abaaababaabaaababbaaaaaaaaaabaaababbbbbbbbabbaaaaabbaabbababbababaaaaababaaaaabbaaabbabbbbabbbaa", 
"aabbbbaabbbbbabbbbbabbaa", 
"bbabababaabaaaabaaaabbaa", 
"babbbbaabaababbbbababbaaabaaaabaaaabbbabbabbbabbbbbbbbaa", 
"abbbabbbabbbaaaabaaaabbbabbbbababbbbaaaabbaababbababbbba", 
"bbbabaaaabbbaaaaaabbbbba", 
"aaaaaabbaaaaaabaaabbaaba", 
"babbbabaaababaabbababbba", 
"abbbbabbbaababaabaaaaababababbab", 
"bbbbaabbbbababaababaabaa", 
"baabbaabbabbaaaabababaaaaaabbaababbaabaa", 
"baababaabaababbabbbbabbb", 
"aabbabbababaabbbabaababb", 
"abaabbbbaaababaaabbaabab", 
"babbbababbbbbabbabaabbbaababbbaabaabaaaa", 
"abbababbbbbbabbabaabaabbaabaabbaababaababaaabaaabbababababbaaaab", 
"baaabbaababbbabbabbabbbaaaaaaaababbbaabaaaabaabaababaabbbbabbaab", 
"baaaaaabbaaaaabbbaabaaaabaabbbabbbbababaabaaaaaabbaaaababaaaaaabaaaabbaa", 
"abaabbbbababbbabaabaabbbbbbaaabaaababbaaabababab", 
"ababaaabaabaabbbbbbbaaaa", 
"baaabbabbabbbaaaaababbbaaabbbaaa", 
"baabababbbbabbbbbbabaaab", 
"abbbaaababaabbbababaaaba", 
"babbaaabaaabbababbaaaaabbbbbbabbbbbaaabaaaababaaaaabbaba", 
"aabbbaaabababbabbabaaaaa", 
"bbaaabbbabaabaabbababbbbbbbbabbbbabbabaabbbbbaaaaaaabbab", 
"abaaaabbabaaaaaaaaababbb", 
"baababaabbbbababbbbaaaaa", 
"babbaaaaaabaabababaabaab", 
"babbbbaabaabbbbbbaaaabbabaabaaaa", 
"bbbbaabbaaababbabaababbb", 
"abbbaaaabbbabbababaabbab", 
"bbaaaabbbbbaababaaaabaababaabbbabbbaaababbaabaaabaababaaaababaabbbbabaabbabaaababaaaaabb", 
"aaabbaaaaaabaabaaabbaaaabbaaabbabababbaabbbabbba", 
"aaabaaabaabababbbabaabbbbbaaabbaaabbbbabbbabbbabbbbaaaab", 
"abbbabbbabbbbbbaaaaaabbb", 
"ababaababbbaaabbabababba", 
"aabbaabaaababbabbaaababa", 
"ababaaabaaaabaabbbabababbbbaabaaaaababbabbbbaabababbaababbbbabba", 
"babbbbbbabaaaaaaababbbba", 
"aaabbbbababbbaaaabaaaaba", 
"ababaababababaaaaabaabbbbababaabaabbbbbbbabaabbbaabababaabaabbab", 
"bbbbbbababaaaabbbbababba", 
"babaabbabbaabbbabbaaabab", 
"aaabaabbababaababbabbbbabaaabbba", 
"bababaabbaabaaaabbababaabbaabaaa", 
"abbbbbbaaabaabbbabaababb", 
"babababbbbababbbbbaabbabbaababaabbbababbbbbbababbabbababaababbaababbabaa", 
"bbbabbabbabbbaaabbababbbabbbaaaabbbbbbabbbbbbababbbbabba", 
"baaabaaaaabaabbaaaabaabbbaaabbaaabbaaaabbbbaaabbabababababababba", 
"ababbaaaabaaaabbabbbaaabbaabbaaaaabaabbb", 
"bbaabaabababbabbabbaaaabbabbbababaababaa", 
"bbababaababaabbbaabbbbabbbbabababababbab", 
"baababaabbaabbaaaaabaaaabaabbabaabaaabaabaaaaaaaaabbbbba", 
"aaababbbaabaaabaaababaaaabababbabbaabaaabbbaabaabaabaaababaaababbabababa", 
"abaaaaaabaabbbbbbababaaaaabaaabaabbbaababbbbabba", 
"bbababaaaababaabababbbabaaabbabbbaaaabbbbaaaababbaaababa", 
"baababababbbabaaaaaaabba", 
"aaabbabaaaabbabbaaabbbbbabaaabab", 
"baabbaaaabbbbabbabaabbbbbaabbabb", 
"abaaabbbbabbbbabaababbbaabbaaabaabaabbbaabbbbaab", 
"ababbabbabaabbbaabbbbbab", 
"bbababbbabaabababbababaababbbbaaaaaaabbaaabbaaabaaaabaaaaaaaababaaaaaaab", 
"aabbbbabbbabbabbbbbaaaba", 
"abababaaabbababbabaabaaa", 
"babbbbbabaaabaabbaaabbbb", 
"abaabbaabaabaaaabaabaaaabbaababa", 
"aababaabbbaabaaabbbaabba", 
"bbababbbaababaabbbbaabbb", 
"baaabaabaaaabaabbababbbb", 
"bbaabaabbaabbaaabaaabbbb", 
"aaababbaababaababbaaaaba", 
"babbbbbbabbbaababaaabbba", 
"babaabbbaababaababaabbab", 
"aaaabbbbababaababbaaabaa", 
"aaaaaabababbbbaababbaaababbabbbb", 
"aaabaaaaaabbabaabbaabaaa", 
"aaaaaabaaaababaaabaaabaa", 
"baaabaaaaabaabbbbbaaabba", 
"abaaaaababaaaabaaaabbbbaaabbbbaaaabaabbaabaababbbabbbaab", 
"baaaaaabbaaaabaaaaaaaabababababbaabbaababababbbbaaaaabaaabbbbbba", 
"aaababaabbaaabaabbabbbabbbaabaaa", 
"bbaaabaaaaaaaaaaaaaaaaababbbabaa", 
"bbbbbaaabbbaaaaabbbaabba", 
"baaabbabbaaaaaabaababbaaabaababaaaaaababaaaaabaababbabba", 
"bbbabbbbbbaabbabaaaabbba", 
"aabaabbbabbbbabbaababbaabaaaabaaaabbbbaaaaabbbaaaaabbbba", 
"abaaaaaabaabbaabbbaaabbbbabaaaaa", 
"aaabbbbbbaabbbbabbbabaab", 
"baabbaabaaabaabaabaaaaaaabababba", 
"aababbabaaabaabbabbbabba", 
"aababaababbbbabbaabaabbaaabababaaaabbbab", 
"abbaaabbbbbbabbabbaaaabbbbaaabbbbbaaaaabbaabbaaabbaababb", 
"aabaabbbababaabaabaabbbbaabbaabb", 
"bbbabaabaaabbaabbbbaabbbbaabaaabbbabbbbabbaaaaabbaababaaaaabbaaabbaaaaaa", 
"baaaaaabbabbbbbbbbaabbabaabbbaab", 
"bbbabbabaaaabbbaaabaabaabaaabababbbabbbbababaaba", 
"aaaaaabbaabaaabaabaababb", 
"abbbaababaabbabaababaaaa", 
"babbaaabbbbbababbabaabba", 
"abbabbbaaaaabaaaaabbababbbbbbaabbaabbaaaaaabbabbbbbaaaabaabbbaababaaabab", 
"aaabbbbbbaaabbaabbabaaab", 
"aaabbabaaaabaabbaabaaabb", 
"bbabbbaaaabaabbababaabbaaabababaaabbbaab", 
"aabbaabaabbaaabaababbababbbaabaababbaababbbbaaba", 
"bbababbbbaaaabbbaabaababbaaaabab", 
"baababaabbaaababbbaabaaaabaabbbaabbbaaaaaaabbabababaabbbbababbabbbaaabbb", 
"babaaaabababbaabbbbaaaab", 
"bbababbbbaabbbbbbabbabab", 
"ababbbaabbbaababaaaaaaab", 
"aababbabbabbbaaababbaaaababbabbbbbaababb", 
"aaabbaaaaabbabbaaabbabaaabbaabaa", 
"abbaaabaabaaaabbaabaababbabbbaab", 
"aaabbaaababbaabababbabba", 
"aabbaabaaaabbbbbaabbbaba", 
"abbaaabbbaaaabbabbabbbba", 
"baaaabbaaababaababababab", 
"bababaababbbbbbaabbabaaa", 
"abbaaaabbbabbababbbaabaaabbbbabbaaabbbaa", 
"bbabbbaaaabbbbaaaaaaaaaa", 
"babbbbbbaaabbabaabbabbbb", 
"abbaaabbbbabbabbaaabbaabaaaaaabbbbbbbbabbaabbaab", 
"bbbbabaababbbaaabbaaabbbaabbaababaabaaba", 
"baabbbabbbbbbbbabbbabaabaabaaabb", 
"aababaabaaabbbbabbbbbaaa", 
"babababbaabaababbaaaaaaa", 
"bbbaabaabbbaaaaabbabbbba", 
"abbabaabaabaaaaabaaaabbbbaaabaaaaaaaabbaaababbbbbbaabbaabbbbaaabbbbbabbb", 
"baabbaabbabbbbaabbaabbaabbabbbaabaabbabb", 
"baaabaabbabbabbbaaaaaaaabbaabaaaaaababbb", 
"baabaabbbbbabaaabbabaabbbbbabaabbbbbabbaaaababbb", 
"bbbbbbabbaababbaaaabbaaabaababbb", 
"babaabbbaabbbbaabababbbbbbbaabbaaaaaaaab", 
"aabaaaabbabbaabbabbaabbbaaaabbabaabababa", 
"aaaaaabaaabbabaabbaabaabaaaabaab", 
"aaabbbbaaaababaabaaabbaaaaaaaabbbabbbaab", 
"abbbbabbaabbbabbabbbaababbbababaabbabaab", 
"bbabbbaabaabbaababaaabab", 
"aababaabaaabbbbbbabaabaa", 
"aaababbaabbaaabbbaabbbab", 
"baabbbbaabbabaababbababbbbabaaabbbbbabaabbaabbaabaababaabbbbabbbbaabbaba", 
"bbaaabbbbabaabbababbbbbbbaabbbbabbbaaaabaaaabbba", 
"bbabababbabbbbbaaaaaabbaaaaabbab", 
"bbaabaabbaabbbbbbbaabaabbabbaabaaabababa", 
"ababbabbaabbbbbbbbabbbbb", 
"aaaaabbbbbabaabbabbabbabbababbaa", 
"aabbabaaaabbaabaabaaaaab", 
"ababbbabaabaaaababaaabbbbaabbbbabbbbaaba", 
"ababbabbaabaabbabaabbbbbaaaaaabbaabaaabb", 
"bbbbbbabbaabbaababbabaaa", 
"abbbaaaaaaabbababaabbaabbaabaabbaaaabaaa", 
"baaaaaabbbaaaabbabaabbbabaabababbabaaaabbaabbbbbbabbbabb", 
"bbaabbbabbbabbaabbaabbbaababababbbababaaaababbbbbaabbbbaababaaababaaabbabababaaaabbbaaaa", 
"aabbbbaabbbaabaababaababbabbabaaabbbbaabbbabaabb", 
"bbababaaaaabbabaaabaaabb", 
"ababababbabbbabababbbaaababababaaaababaaabbbabbbababbbaabaabbbaa", 
"baaaabaaaaaaababbbabbbbabbaaabaaabaabaabaaababbbbaaabbbbaabaaaba", 
"baabbaaaaabababbbaabaaaababaabaaaaabababbbabbaaa", 
"bbbaaaabbbaaaaabbaabbbabaabbaabbabbbabab", 
"baabbbbbaababaaaabbbabaaabbbbaaaabababba", 
"ababbaababbbaaaaaaaaabbb", 
"abbbabbbabbbabaaabbaaabbbbbabaaabbaaaaba", 
"aaabaabaaaabbabaabbaabaa", 
"aabababaabbabababaaaaabbbbbbaabbaabbbbbbabbaabbbbaabaaabbbbbbaabbbaabbbb", 
"baabbbaabaabbabaabababaaabaaaaab", 
"abababaabbabababbbbaabba", 
"aaabbaaabaabaaabababbaababbababa", 
"aaabbbbababbbababaaababb", 
"babbaaaaaaabbabaaabbaaabbbabbbbb", 
"baabbaaabbaabbabaaabbabbaaabbbbabaabbbbbabbbbbaaaaaaababbabbbabb", 
"bbbbaaabbaabaaabbababbababaababaaabaabaa", 
"baabbbbababbbabababbbaab", 
"babbbbaaaabaabababbabbbb", 
"abababaababaaababaabaaabbbbbbabbbbababbabbababaabbbaaaaa", 
"aaabaabababbbbabbbaaabbaaaaabaabbbbaababbaaaaaaa", 
"bbaaabbbaaababbabbabaabb", 
"bbbaabaaaabababbababaaaa", 
"baababaaaabbabbaababababaaabbaaaabbaabbbbbaaaaba", 
"aabaaabaaaaabaabaaabaabbbaaaaaaababbaaba", 
"abababaaabaaabaaabaababa", 
"babbaabbababaabbaaabbbaa", 
"abbaaaaabaaabbaabbbaabba", 
"bbabaaaabaabaaabbbbbaabbabbabababaaababbbaabbaabbbabbabaaabbabaaababbabbbabbbabb", 
"ababbabbaaababbabababbbbbbabaabbbbbbabbaaabbbaab", 
"aabababaababbabbbaaababaaabbabbaabbbbbaabbabbbbaaaababbababbbbba", 
"aabbabbbbbaaabbabaaabbba", 
"ababbaababbaaaaabbabababbbaabbaa", 
"bbbabbbbbbabababaaabbbba", 
"abbaaababababbaabaaaaabb", 
"aabbababbbababababbaabab", 
"bbaabbabaababbbaabababab", 
"baabababaabbabbabbabbbab", 
"bbababaaaabbbbbbbbabbbba", 
"ababaababbbaaabbbabaabaa", 
"baaaabbbbaabbaaaabbbaaabbabbbabbabaabbab", 
"aabbbbbbabbaababbabbbaaabbbaabbbabaababa", 
"baababaabababaaababbbbabbaaababa", 
"babababbbaabbbbbbbaaabaa", 
"babbbaabbaaaababbabaabaabbbaaaaaaaababaa", 
"aabbbbbbbabbbbbbabaabbab", 
"aaaabbbbaabaabababbbabba", 
"aabaababaabaababbbbaaaab", 
"abaabbbbababbaababbbbbbaabababab", 
"babbbbbbabbababbaababbbb", 
"abbabbbabaabbbaabbabbbbaaabbbaaaabbababa", 
"bababbabaaabababaabbabaaabababbbabbaaaababbbabbaaababaabababbbaaaaabbaaa", 
"aabbababaabbaababbaaabbabbabbbaaabaaaabbaaaabaaaaabbbaaa", 
"babbbbbbaabbaaaabaabbbab", 
"baabaaaabbaaaabbabaaaabbabaaabbbaabbbbaababbbabb", 
"bbaabbabbaabbaaabaaaabaa", 
"bababaababaaaaaaaabaababaabbabaababbbbbabbbabaabbbbbbaab", 
"baababbabaababbabaaaaabb", 
"baabbbaaaaaabbbabaaaaaaaaabbbaabbaabaabaabaababa", 
"aabbaabaaababbbabbbabbabaababbbbabbbaabb", 
"abbbbababbabbaabaabaabaaaaaabbbbaababbbaaabbabbb", 
"abaaabbbabbababbaabbbaaa", 
"bbabbabaaababbbaabbbaabaaabbbbbbabbabaaabbbbbabababbbabb", 
"aabaababbbbaabaaaaaabbbbabbaaaaabaababbbbababbbaabaababababaabaa", 
"aabaabaabbbababaabbbabbaaababbbb", 
"aaaaabbabbababaaabaababaaaaaabaaaababbba", 
"bbaaaaababbbbababaabababaababbabbbabbbabbbaaabbaaaabbaababbbaababbaabbaabbbaabaa", 
"babaabbbbbabbabababbaaaabbbabbaa", 
"aaabaaaaaaaababaabbbbbbaaaaabbbabbbaabbaaaabbbaa", 
"babbbbabababaaabaabbbaaa", 
"bbbbaaabbbbbbabbbbaabbabaabbabababaabaab", 
"bbabbbbbbbaabbbbbaaaaabbbbbababbbaaababbabaababbabbabbaabaabaaab", 
"abbabbbaaaabbabbabbbaabaaabaaabbabbbbbaa", 
"aaabbaaaabababaaaaababbaaababbbabbbbababaaaaabab", 
"abaabbaaaaababbabababbbb", 
"aaabaabbaababaaaabbabbbabaaabbbbbbbbbaba", 
"bbbbaaabbbabbabaabbbbaaa", 
"ababaaabbbababababbbabba", 
"bbbabbbbaaaaaabbaaaababa", 
"baabbbbbbbbbaaabbababbaa", 
"aaabbbabbababababaaaaaaa", 
"baabbbabbababbabaaabbaababbaaabbabbbbbab", 
"bbabbababaabababbbaaabaa", 
"bbabbabaaabbaababbabaababbbaabbbabaaaaba", 
"abaabbaaabbaaabaabbaaaaa", 
"baabbbbaaaabbbabbaabbbbbababbbaabbbbbbbbbbaabaababaabaab", 
"aabbabaababaabbaabbbabba", 
"abbbabaabababaabababaaaa", 
"bbaabbabbbabbbaabbbaabbb", 
"baaabbabaabbabbaabbbabbbabbabbbabaabbabababbabbbaabbaaabbbabaaaaaabababababababa", 
"aabaaaabbbbabaababbaabbbaaabbaaababbbbabaaaabbbaaabbbbabbaabaabb", 
"abaabaaabababbabaaaababb", 
"babaabbbaaababbbbbabaaba", 
"abbbbabbbaabbbbaabbabaaa", 
"aabbabaabaabbbaababbabaa", 
"babbbbbbbaabaaababaaabab", 
"ababbaaabbaabbaababababbbbababbbbbbbabbbaaaaaaab", 
"baaaaabaababbbabbabaaaaaaababbabaaababbabbababbbbabaabba", 
"baaaaabaaabababbbabaaaaa", 
"bbaaabbababbbbbbaaabaaabbaaaabab", 
"aaaaaababbabababbbaababa", 
"abbabbbabaabaaabbbbbbbba", 
"abbbbabbbabbbabaabaaabbbabbbbabbaaabbbabaaaaabba", 
"bbbabaabbabbaababaaaabaabaabbabbaababbbabbaaaaabbbbaababaaababbb", 
"bbaaaabbabababbbbbbbbaab", 
"baabaaabbabbaabbaabababa", 
"babbbbbabaabaabbbabaaaaa", 
"babbbaaaababaabbabbaaaaaaabbbbab", 
"baaabbabbaabaabbabbbaaaaaaaaaabbaaabbbbbbabaabab", 
"ababaaaaaaaaaaaaababaaaaabaaabab", 
"bbbbbbabaababaabbbaabaabbbababba", 
"bababaaaaaabaabbbabababa", 
"bbabababaaabbabaaabbababbbbababb", 
"baabbabaabaabbbabbbaababaaabbabbbabbabbabbabaaaa", 
"abbbabbaabbaabbabbbaabbbbabbbbbaaabbbaabaababbababaaababababaaabbbabbbab", 
"ababbaabbabbaabaabbbbbbbbabaabaabbaaaaabbabababb", 
"abababaabaaaaababaababaaabbaaababbbbabbbbbabaabbabaaababaabbaabbaabaaabb", 
"ababbaababbaaaaabaabbbbbaaaaabaaabbababbbababbbababbaaabbaabbaba", 
"aabbabbbaaabaabbabaabbbbbbbbbaab", 
"baaaabbaaaababaaabbaabbb", 
"aababaabbaaabbaaaaaabaababaabbbbbbbbbaaa", 
"bbaabaabbabaaabbbababbababbbabbaaabaabbaabbaaaaaabbbaababbbbabaabbaaaaabbababbaa", 
"aababaabaababaababbaabab", 
"bbaaababbbbaaaaaabbaabababaaababbbbaabaa", 
"abbaabbaabbaabbababbabab", 
"babbabaabababaabaababbaaabaabaabaaabaabbabbababbaaabbbbaabbaaaaaaababaab", 
"ababaaababbbbbbaaababbbb", 
"bbbbbbbababaabaaabbabaab", 
"baaabaabbabbbbaaaaaaabbb", 
"ababaabbaaabbabbaaaaabab", 
"bbaabbbaaaaabbabaabbbaba", 
"abbaaabbbbbbbabbabaabbaababbbbbbbabbababbababbbb", 
"baaaabbaabbaaaabaabbabababaaaaaaabbaabaa", 
"abbabbbaaaabbaaaabababab", 
"aabaababababaabbbabbabaa", 
"abaaaabbbaabaaabaaabbbaa", 
"aabbabbbbbbaaabbaaaabbab", 
"ababaabbaabbaaaabbaaaaab", 
"abbbbbaabbbbbbbaaabbaabb", 
"abaabbbaaaabbbbbabaabbab", 
"babaaabbbabbbbaabaaaaabbbbbabbaabaabbaaa", 
"babaabbbbaababaaaabbaaab", 
"aaabaaaaaabbbababbbaabbabbabbaab", 
"aabbabaaababbbaabbaaabab", 
"abbaaaabbabababbbbbbbbbb", 
"baaabbaaababaaaaababaabbbbabbbaabbbaababbabbbbabbaaaabbaaabababbabaaabbababaaaabbaababbb", 
"ababaaabbbbabbbbbaabbabaaaaaabaa", 
"aaababbaabbababbaababaaabaababbabbbaabaababbabba", 
"baabbbbbabbbbbbaabaabbbbbaaaabbaaabbaabaaabaaabaabaabbab", 
"aabbbbbaaabababbbbbaaabaaababbaabababaabbaabababbaabbabbaabaababbbabbaabaabbaaba", 
"baabaaaaaaaabaababbaabbb", 
"aabaabbbbabbaabbbaababbb", 
"abbaaabaaabbabbaaaaaaabbaaaaabab", 
"baabbbbaaaabaaabaaababaaaabbaabb", 
"abbabbbaabababaaababbbba", 
"aaaabbbbbbaabbabaabbaabb", 
"baabaaababbbaabaabbbbbaa", 
"abbaaabaaabaababbbabaaaa", 
"bbababaaaabaaaabbabbbbbbababbbbbbbbbaabaabbbbaba", 
"aabbbbaaaaaaaababaaababa", 
"bbbabbabaabaaaabbababaabbbaabaabbbaaaaaaaabbbaabbbbabaab", 
"babababaabbbababbbbbbaaababaaaababbaaabababbaaaaaababbbabbbabaabbaaaababaaaaabbb", 
"aaababbaaabaaabababbaabbbbabababababaaabbbababba", 
"bbaabbabababaababaaaaaaa", 
"bbbaababbabbbbbabbbbaaaa", 
"baabbaababbabbbabbaaabbbbbbbaabbbaabaaaabbaabbbb", 
"ababbbababaabbaabababbab", 
"aaabbaaaabbaaabbabbaabab", 
"bbaabaaaabaabbbbbbbaabaabbbbbaaabababbbaabbabbbbaababbab", 
"babbbabababbbababbbabbba", 
"abbbbabbbbababaaabaabaab", 
"abababbbabbbabaabbbbababababbabaaaabaaaaaaaaaababbbbbaabbaaabbbb", 
"babaabbaaaaabbbbabbbbaab", 
"baabaabbbabaaaabaabbababbbaaabaa", 
"baaaaaababaaaaaabbaabbabaabbaaaabaaaababbaabaaba", 
"aabbaaaaabaabbbbabaaaaab", 
"aaababbbabaababbabbbaabbbababaaaaaabbabbbbabbabaabababbbbbbababbabbbbaabbabababb"
}
return {grammar = grammar, input = input}
